version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: style-my-closet
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge