version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: style-my-closet
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - my-network

  redis:
    image: redis:7.2
    command: ["redis-server"]
    container_name: closet_redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  postgres-data:
  redis-data:

networks:
  my-network:
    driver: bridge