spring:
  flyway:
    enabled: true
    baseline-on-migrate: false
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  cloud:
    compatibility-verifier:
      enabled: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
  sql:
    init:
      mode: never

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

resilience4j:
  circuitbreaker:
    instances:
      crawling:
        failureRateThreshold: 50
        waitDurationInOpenState: 3s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
  ratelimiter:
    instances:
      crawling:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0s
  retry:
    instances:
      crawling:
        maxAttempts: 2
        waitDuration: 500ms
        retryExceptions:
          - org.springframework.web.client.ResourceAccessException

external:
  market-index:
    service-key: ${SERVICE_KEY}
    base-url: https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
    num-of-rows: 100
  kakao:
    rest-api-key: ${REST_API_KEY}
    base-url: https://dapi.kakao.com/v2/local/geo/coord2regioncode.json