spring:
  flyway:
    enabled: true
    baseline-on-migrate: false
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
  sql:
    init:
      mode: never

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

style-my-closet:
  storage:
    type: ${STORAGE_TYPE:local}  # local | s3 (기본값: local)
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:.stylemycloset/storage}
    s3:
      access-key: ${AWS_S3_ACCESS_KEY:access-key}
      secret-key: ${AWS_S3_SECRET_KEY:secret-key}
      region: ${AWS_S3_REGION:region}
      bucket: ${AWS_S3_BUCKET:bucket}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}