spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 60000
  batch:
    jdbc:
      initialize-schema: always
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

management:
  health:
    mail:
      enabled: false

logging:
  level:
    com.stylemycloset: DEBUG
