spring:
  flyway:
    enabled: true
    baseline-on-migrate: false
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
  sql:
    init:
      mode: never
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${CLOSET_ADMIN_EMAIL_ID}
    password: ${CLOSET_ADMIN_EMAIL_PASSWORD}
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

closet:
  admin:
    username: ${CLOSET_ADMIN_USERNAME}
    email: ${CLOSET_ADMIN_EMAIL}
    password: ${CLOSET_ADMIN_PASSWORD}


external:
  market-index:
    service-key: ${SERVICE_KEY}
    base-url: https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
    num-of-rows: 100
  kakao:
    rest-api-key: ${REST_API_KEY}
    base-url: https://dapi.kakao.com/v2/local/geo/coord2regioncode.json

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}
    access-token-validity-seconds: ${SECURITY_JWT_ACCESS_TOKEN_VALIDITY_SECONDS}
    refresh-token-validity-seconds: ${SECURITY_JWT_REFRESH_TOKEN_VALIDITY_SECONDS}

